login:
    resource: "@AdminBundle/Controller/"
    type:      annotation
login_check:
    path:   /login_check
logout:
    path:   /logout

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
