login:
    resource: "@AdminBundle/Controller/"
    type:      annotation
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
