parameters:
#    parameter_name: value

services:
    default.locale_listener:
        class: DefaultBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    form.type.registration:
        class: DefaultBundle\Form\Type\RegistrationType
        arguments: []
        tags:
          - { name: form.type, alias: registration}
