parameters:
#    parameter_name: value

services:
    default.locale_listener:
        class: DefaultBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
